
.TH beings 1 "January 5, 2017"
.SH NAME
beings \- Scaleable multibeings simulator with individual AI.
.PP
.SH SYNOPSIS
beings
.PP
.SH DESCRIPTION
A simple AI simulation where each individual takes decisions depending on the close surrounding and other beings.
.PP
.SH How-to
During simulation: "," and "." to change the number of beings. "+" and "-" to change simulation speed.
.PP
.SH BUGS
No known.
.PP
.SH AUTHOR
schnitz (https://github.com/schnitz81)
